---
title: "lowgrad_misc_analyses"
author: "glemley"
date: "11/2/2021"
output: html_document
---


```{r}
library(tidyverse)
# library(readxl)

root.dir <- rprojroot::find_root("lgss.Rproj")

sites.events <- read_csv(file.path(root.dir, "data", "compile_2015-2019", "field_data", "final_cleaned", "sites_events_final_2021-11-02.csv"))

field <- read_csv(file.path(root.dir, "data", "compile_2015-2019", "field_data", "final_cleaned", "2015-2019_lowgrad_fielddata_20210526.csv")) %>% 
  mutate(event_id_date = as.Date(sample_date, format = "%m/%d/%Y"),
         event_id_date = format(event_id_date, "%Y%m%d"),
         event_id = paste0(site_id,"_",event_id_date)) %>%   
  filter(event_id %in% sites.events$event_id) %>% 
  # Convert habitat sampled fields to -9999 if NA
  mutate(lgs_habitat_bank = ifelse(is.na(lgs_habitat_bank), -9999, lgs_habitat_bank),
         lgs_habitat_macrophyte = ifelse(is.na(lgs_habitat_macrophyte), -9999, lgs_habitat_macrophyte),
         lgs_habitat_snag = ifelse(is.na(lgs_habitat_snag), -9999, lgs_habitat_snag),
         lgs_habitat_substrate = ifelse(is.na(lgs_habitat_substrate), -9999, lgs_habitat_substrate),
  ) %>% 
  # Fill incomplete habitat sample entries (-9999) to 0 where substrate samples were collected
  mutate(lgs_habitat_snag = ifelse(lgs_habitat_snag == -9999 & lgs_habitat_substrate != -9999, 0, lgs_habitat_snag),
         lgs_habitat_macrophyte = ifelse(lgs_habitat_macrophyte == -9999 & lgs_habitat_substrate != -9999, 0, lgs_habitat_macrophyte),
         lgs_habitat_bank = ifelse(lgs_habitat_bank == -9999 & lgs_habitat_substrate != -9999, 0, lgs_habitat_bank))


```

```{r}
# Determine percentage of sites where woody snag habitats were present
field.habitat <- field %>%
#   ##Clean up snag field
#   mutate(lgs_habitat_snag = ifelse(lgs_habitat_snag == -9999 & lgs_habitat_macrophyte != -9999, 0, lgs_habitat_snag),
#          lgs_habitat_bank = ifelse(lgs_habitat_bank == -9999 & lgs_habitat_macrophyte != -9999, 0, lgs_habitat_bank)) %>% 
  # Filter out records where all habitat fields are blank (substrate is blank for all of these)
  filter(!lgs_habitat_substrate %in% "-9999")

h.snag.present <- field.habitat %>% 
  filter(lgs_habitat_snag %in% c(1,2))
h.bank.present <- field.habitat %>% 
  filter(lgs_habitat_bank %in% c(1,2))
h.substr.present <- field.habitat %>% 
  filter(lgs_habitat_substrate %in% c(1,2))
h.macroph.present <- field.habitat %>% 
  filter(lgs_habitat_macrophyte %in% c(1,2))

nrow(h.snag.present)/nrow(field.habitat)
nrow(h.bank.present)/nrow(field.habitat)
nrow(h.substr.present)/nrow(field.habitat)
nrow(h.macroph.present)/nrow(field.habitat)

# Snags only present at 76% of sites!

```

