---
title: "plot_ibi_2022-12-21"
author: "glemley"
date: '2022-12-21'
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggh4x)

# Import final metric scores and training/test site vectors
dir.ibiplot_dfs <- file.path(here::here(), "data/IBI/df_exports_for_IBI_plot")

metrics.scores <- read.csv(file.path(dir.ibiplot_dfs, "metrics.scores.df_2022-12-21.csv"))
train.df.vec <- read.csv(file.path(dir.ibiplot_dfs, "train.df.vec_2022-12-21.csv"))
test.df.vec <- read.csv(file.path(dir.ibiplot_dfs, "test.df.vec_2022-12-21.csv"))

```


```{r}



# Add groups to scores table

metrics.scores.plot <- metrics.scores %>% 
  mutate(class = case_when(
    condition_class == "1" ~ "LD",
    condition_class == "2" ~ "ID",
    condition_class == "3" ~ "MD",
  ),
  group = case_when(
    site_id %in% train.df.vec$x ~ "Training",
    site_id %in% test.df.vec$x ~ "Validation",
    TRUE ~ "Other"
  ))


# p <- qplot(displ, hwy, data = transform(mpg, cyl = as.character(cyl)))
# cyl6 <- subset(mpg, cyl == 6)
# p + geom_boxplot(data = transform(cyl6, cyl = "7"), colour = "red") +
#   geom_boxplot(data = transform(mpg, cyl = "all"), colour = "blue") +
#   facet_wrap(~ cyl)
# 
# 
# metrics.scores.plot %>% 
#   mutate(condition_class = factor(class, c("LD", "ID", "MD"))) %>% 
#          # group = factor(group, c("Training", "Validation"))) %>% 
#   ggplot(aes(condition_class, SITE_SCORE)) +
#   coord_cartesian(ylim = c(0, 10)) +
#   geom_boxplot() +
#   facet_grid(~group, margins = T, drop = F) 
#   # ggpubr::theme_pubr()
# 
# 
# mpg %>% 
#   # mutate(cyl = factor(class, c("1", "2", "3"))) %>% 
#   ggplot(aes(displ, hwy)) +
#   # coord_cartesian(ylim = c(0, 10)) +
#   geom_boxplot() +
#   facet_grid(~cyl, margins = T) 
#   # ggpubr::theme_pubr()
# 
# data(mpg)

# metrics.scores.plot %>%
#   mutate(condition_class = factor(class, c("LD", "ID", "MD"))) %>%
#          # group = factor(group, c("Training", "Validation"))) %>%
#   ggplot(aes(condition_class, SITE_SCORE)) +
#   coord_cartesian(ylim = c(0, 10)) +
#   geom_boxplot() +
#   facet_grid(~group, margins = T, drop = F)


```

```{r}
CreateAllFacet <- function(df, col){
  df$facet <- df[[col]]
  temp <- df
  temp$facet <- "All sites"
  merged <-rbind(temp, df)

  # ensure the facet value is a factor
  merged[[col]] <- as.factor(merged[[col]])

  return(merged)
}

# df <- CreateAllFacet(mpg, "cyl")
# 
# ggplot(data=df, aes(x=displ,y=hwy)) +
#   geom_point(aes(color=cyl))  +
#   facet_wrap(~ facet) +
#   theme(legend.position = "none")
# 




# df3 %>% 
#   mutate(condition_class = factor(class, c("LD", "ID", "MD")), 
#           facet = factor(facet, c("Training", "Validation", "All sites"))) %>% 
#  ggplot(aes(condition_class, SITE_SCORE)) +
#   coord_cartesian(ylim = c(0, 10)) +
#   geom_boxplot()  +
#   # facet_wrap(~ facet, scales = "free") +
#   facet_wrap2(~facet,  # ggh4x package for nested facets
#               strip = strip_nested(),    # sub facets normal
#               scales = "free", axes = "margins",
#               remove_labels = "all") +
#   facetted_pos_scales(
#     y = list(COL == 2 ~ scale_y_discrete(),
#              COL == 3 ~ scale_y_discrete())
#   )
# 
# df3 %>% 
#   mutate(condition_class = factor(class, c("LD", "ID", "MD")), 
#           facet = factor(facet, c("Training", "Validation", "All sites"))) %>% 
#  ggplot(aes(condition_class, SITE_SCORE)) +
#   coord_cartesian(ylim = c(0, 10)) +
#   geom_boxplot()  +
#   # facet_wrap(~ facet, scales = "free") +
#   facet_wrap2(~facet,  # ggh4x package for nested facets
#               strip = strip_nested(),    # sub facets normal
#               scales = "free",
#               remove_labels = "all")
# 


df2 <- CreateAllFacet(metrics.scores.plot, "group")
df3 <- df2 %>% 
  filter(!((group %in% "Other") & (facet %in% "Other"))) %>% 
  mutate(condition_class = factor(class, c("LD", "ID", "MD")), 
          facet = factor(facet, c("Training", "Validation", "All sites"))) 

labels <- data.frame(f=letters[1:3], label=LETTERS[1:3])


# df3 %>% 
p <- ggplot(df3, aes(condition_class, SITE_SCORE)) +
  coord_cartesian(ylim = c(0, 10)) +
  geom_boxplot()  +
  # facet_wrap(~ facet, scales = "free") +
  facet_grid(~facet, scales = "free", space = "free") +
  facetted_pos_scales(y = list(~ scale_y_discrete(guide = 'none'))) +
  # geom_label(data = c("A",), aes(label=label), 
  #           x = Inf, y = -Inf, hjust=1, vjust=0,
  #           inherit.aes = FALSE) +
  # theme(legend.position = "none") +
  xlab("Condition class") +
  ylab("LGBAP") +
  # ggpubr::theme_pubr()
  # theme_classic()
  # theme_minimal()
  # theme_bw() +
  theme(strip.text = element_text(size=10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10))

# Plot without panel tags:
p

# Plot with panel tags:
egg::tag_facet(p, 
          x = -Inf, y = -Inf, 
          vjust = -1,
          open = "", close = "",
          tag_pool = LETTERS,
          fontface = 2,
          size = 4,
          )


# for final plot export:
  # ggsave(file.path(here::here(), "data/ibi/plots_for_pub", "IBI_2022-12-22.tiff"),
  #        dpi = 400,
  #        device = "tiff",
  #        width = 5,
  #        height = 4)


```



```{r old plots}
metrics.scores.plot %>% 
  filter(site_id %in% train.df.vec$x) %>% 
  mutate(condition_class = factor(class, c("LD", "ID", "MD"))) %>% 
  ggplot(aes(condition_class, SITE_SCORE)) +
  coord_cartesian(ylim = c(0, 10)) +
  geom_boxplot() +
  # geom_jitter() +
  ggtitle("Training") +
  # xlab(NULL) +
  xlab("Condition Class") +
  ylab("LGBAP Score") 
  # geom_hline(yintercept=imp_thresh, color = "red") 
  # geom_hline(yintercept=4.37, color = "blue") +
  # geom_hline(yintercept=4.8, color = "green") +
  # geom_hline(yintercept=5.79, color = "purple")

  # ggsave(file.path(root.dir, "data/ibi/plots_for_pub/rescaling", "ibi_training_MAD_2021-12-31.png"), dpi = "print")

# Plot validation final scores
metrics.scores.plot %>% 
  filter(site_id %in% test.df.vec$x) %>% 
  mutate(condition_class = factor(class, c("LD", "ID", "MD"))) %>% 
  ggplot(aes(condition_class, SITE_SCORE)) +
  coord_cartesian(ylim = c(0, 10)) +
  geom_boxplot() +
  # geom_jitter() +
  ggtitle("Validation") +
  xlab("Condition Class") +
  ylab("LGBAP Score") 
  # xlab(NULL) +
  # ylab(NULL) +
  # theme(axis.text.y = element_blank(),
        # axis.ticks.y = element_blank()) +
  # ggsave(file.path(root.dir, "data/ibi/plots_for_pub/rescaling", "ibi_validation_MAD_2021-12-31.png"), dpi = "print")

# metrics.scores.val <- metrics.scores.plot %>% 
  # filter(site_id %in% test.df.vec) 

# Plot validation + class 2 (all data plotted minus training) final scores
# metrics.scores.plot %>% 
#   filter(!(site_id %in% train.df.vec)) %>%
#   mutate(condition_class = factor(condition_class, c("1", "2", "3"))) %>% 
#   ggplot(aes(condition_class, SITE_SCORE)) +
#   coord_cartesian(ylim = c(0, 10)) +
#   geom_boxplot() +
#   ggtitle("Final scores (val + class 2)") +
#   xlab("Condition Class") +
#   ylab("LG-BAP Score")

# plot all final scores
metrics.scores.plot %>%
  mutate(condition_class = factor(class, c("LD", "ID", "MD"))) %>% 
  ggplot(aes(condition_class, SITE_SCORE)) +
  coord_cartesian(ylim = c(0, 10)) +
  geom_boxplot() +
  # geom_jitter() +
  ggtitle("All Sites") +
  # theme(axis.text.y = element_blank(),
  #       axis.ticks.y = element_blank()) +
  # ylab(NULL) +
  # xlab(NULL) +
  xlab("Condition Class") +
  ylab("LGBAP Score") 
  # ggsave(file.path(root.dir, "data/ibi/plots_for_pub/rescaling", "ibi_allsites__MAD_2021-12-31.png"), dpi = "print")


# Plot all scores, single box and whisker to visualize distribution against scale
metrics.scores.plot %>%
  # mutate(condition_class = factor(condition_class, c("1", "2", "3"))) %>%
  ggplot(aes(condition_class, SITE_SCORE)) +
  coord_cartesian(ylim = c(0, 10)) +
  geom_boxplot() +
  # geom_jitter() +
  ggtitle("All Sites") +
  # theme(axis.text.y = element_blank(),
  #       axis.ticks.y = element_blank()) +
  # ylab(NULL) +
  # xlab(NULL) +
  xlab("Condition Class") +
  ylab("LGBAP Score") 
```

